### PR TITLE
fix: NPM packages cannot be published

### PR DESCRIPTION
**Pull request by carstencodes**
in #356 it was mentioned, that the upload did not
work.
First issue seems to be, that the package.json cannot be found. The root cause seems to be, that the
working directory is not correct.

This should work

### CODE REVIEW

**Review by yoheimuta — APPROVED** [review]
Thank you 👍

**Comment by AlexCannonball** [comment]
@carstencodes Hello, I guess it didn't succeed after this fix.

As I guess from `npm ERR! code ENEEDAUTH` and https://stackoverflow.com/questions/75357158/github-actions-npm-publish-fails-with-err-code-eneedauth `registry-url` is also needed.

**Comment by carstencodes** [comment]
The log points out, that the correct registry URL is set.

According to https://stackoverflow.com/questions/24143973/npm-adduser-via-bash the environment variable `NPM_EMAIL` needs to be set as well, e.g. from secrets. This is a secret that only @yoheimuta should know.

**Comment by yoheimuta** [comment]
@carstencodes Thank you for checking the failure.

I've added `NPM_EMAIL`.

image

**Comment by carstencodes** [comment]
And now I am ashamed and embarrassed. I should have read the entire manual...

**Comment by yoheimuta** [comment]
@carstencodes No worry. I appreciate your contribution 👍 
Can you check https://github.com/yoheimuta/protolint/actions/runs/7269554079/job/19807349452 when you have a moment? Does it mean `npm adduser` is required on CI?

**Comment by carstencodes** [comment]
@yoheimuta This command is interactive and hence not meant for CI processes.

After looking at https://stackoverflow.com/questions/24143973/npm-adduser-via-bash again, I should have added these two variables in .npmrc.

I've added #360 to save credentials to a project local .npmrc.

Uploading python wheels and nuget packages is more easy ...

**Comment by carstencodes** [comment]
Ok, I read the wrong version of the documentation. I read for npm 6, latest is npm 9. This uses scoped tokens, therefore the url part must be added to the npmrc.

**Pull request merged**
