### PR TITLE
feat: Added python publishing

### LINKED ISSUE #338: [Distribution] Add support for Python
When building python protobuf serializers, gRPC services or grpc clients, the proto files are actually generated during the build using the `Protobuf` collection.

This project is already shipping a maven package. It should be possible to ship a wheel package as well.

Steps to take:

- [x] Add packaging information for a python wheel
- [x] Add a module index for running as a python module.
- [x] Pack wheel package after go-releaser has run
- [x] Upload wheel package to pypi.org 

I could help with the first three bullet points. I think the last point is up to the maintainer.

### PR DESCRIPTION
**Pull request by carstencodes**
- Added binary distribution folder for PY
- Added scripts to build python binary wheel package
- Added new configuration source: Python pyproject.toml for Python
- Added CI Pipeline for publishing Wheel packages after `goreleaser` job/workflow has finished
  - **NOTE** A secret called PYPI_USERNAME (usually __token__) and PYPI_AUTH_TOKEN (usually a token from pypi) must be provided by @yoheimuta to upload the package to pypi.org

Closes #338

### CODE REVIEW

**Review by yoheimuta — APPROVED** [review]
Thank you for your excellent contribution!
Sorry for the late response 🙇‍♂️ 

I'm dealing with PYPY setup later.

**Comment by carstencodes** [comment]
You're welcome. I think I will start on #337 soon.

**Comment by yoheimuta** [comment]
> A secret called PYPI_USERNAME (usually token) and PYPI_AUTH_TOKEN (usually a token from pypi) must be provided

I added these secrets to Actions secrets.

image

**Comment by yoheimuta** [comment]
@carstencodes [The Publish Wheel Package action](https://github.com/yoheimuta/protolint/actions/runs/8258333947/job/22590382199) was successful, but the publishing step was skipped. Is there something off with [the condition](https://github.com/yoheimuta/protolint/pull/358/files#diff-2bde46370152d1157b9610de61440dc00f39e893eed722a7b6b277e338dbd972R52)?

**Comment by carstencodes** [comment]
@yoheimuta Yeah, gorramn copy&paste error. cf. to #370

**Pull request merged**
